//! Owner-scoped D1 migrations. Runtime verification never writes.
//! All operator mutations use one primary D1 batch, including history guards.
use futures::future::LocalBoxFuture;
use lenso_migration::{AppliedMigration, Migration, MigrationPlan};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

const LEDGER: &str = "_lenso_migrations";
const CREATE_LEDGER: &str = "CREATE TABLE IF NOT EXISTS _lenso_migrations(owner TEXT NOT NULL, backend TEXT NOT NULL CHECK(backend='d1'), version INTEGER NOT NULL, name TEXT NOT NULL, checksum TEXT NOT NULL, PRIMARY KEY(owner,backend,version))";
const CREATE_GUARD: &str =
    "CREATE TABLE IF NOT EXISTS _lenso_migration_guard(value INTEGER NOT NULL CHECK(value=1))";
const USER_TABLES: &str = "SELECT name FROM sqlite_master WHERE type='table' AND name NOT GLOB 'sqlite_*' AND name NOT GLOB '_cf_*' AND name NOT IN ('d1_migrations','_lenso_migrations','_lenso_migration_guard')";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Statement {
    pub sql: String,
    pub params: Vec<Value>,
}
impl Statement {
    pub fn new(sql: impl Into<String>, params: Vec<Value>) -> Self {
        Self {
            sql: sql.into(),
            params,
        }
    }
}

/// Implement with the primary binding's atomic batch API. Never retry writes.
///
/// Return one row vector per statement in order (including empty write results).
/// Reject unsuccessful statement results or malformed receipts as [`Error::Transport`];
/// the adapter must not turn a failed D1 result into an empty successful result.
pub trait Transport {
    fn batch(
        &self,
        statements: Vec<Statement>,
    ) -> LocalBoxFuture<'_, Result<Vec<Vec<Value>>, Error>>;
}

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("invalid authored D1 migration plan")]
    InvalidPlan,
    #[error("D1 migration history is absent; explicit setup or legacy adoption required")]
    SetupRequired,
    #[error("D1 schema requires explicit upgrade")]
    UpgradeRequired,
    #[error("D1 migration history differs from the authored plan")]
    History,
    #[error("refusing to adopt an unmanaged D1 database")]
    Unmanaged,
    #[error("D1 storage operation failed; a submitted write may have committed")]
    Transport,
    #[error("D1 migration exceeds the bounded batch capacity")]
    Capacity,
}

/// Byte offsets generated by a SQLite-aware authoring tool, never runtime SQL splitting.
#[derive(Debug, Clone, Copy)]
pub struct SqlMigration {
    pub migration: Migration,
    pub statement_ends: &'static [usize],
}

/// Explicit compatibility input for one already-applied Auth-style v1 schema.
#[derive(Debug, Clone, Copy)]
pub struct LegacySchema {
    pub table: &'static str,
    pub fingerprint: &'static str,
}

#[derive(Debug, Clone)]
pub struct Plan {
    owner: &'static str,
    migrations: &'static [SqlMigration],
    common: MigrationPlan,
    legacy: Option<LegacySchema>,
}

impl Plan {
    pub fn new(
        owner: &'static str,
        migrations: &'static [SqlMigration],
        common: &'static [Migration],
        legacy: Option<LegacySchema>,
    ) -> Result<Self, Error> {
        if owner.is_empty() || owner.len() > 128 || migrations.len() != common.len() {
            return Err(Error::InvalidPlan);
        }
        for (entry, original) in migrations.iter().zip(common) {
            if entry.migration.checksum() != original.checksum() || entry.statement_ends.is_empty()
            {
                return Err(Error::InvalidPlan);
            }
            let mut start = 0;
            for &end in entry.statement_ends {
                if end <= start
                    || original
                        .sql()
                        .get(start..end)
                        .is_none_or(|s| s.trim().is_empty())
                {
                    return Err(Error::InvalidPlan);
                }
                start = end;
            }
            if start != original.sql().len() {
                return Err(Error::InvalidPlan);
            }
        }
        if legacy.is_some_and(|v| {
            v.table.is_empty()
                || !v
                    .table
                    .bytes()
                    .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
        }) {
            return Err(Error::InvalidPlan);
        }
        Ok(Self {
            owner,
            migrations,
            common: MigrationPlan::new(common).map_err(|_| Error::InvalidPlan)?,
            legacy,
        })
    }

    fn ledger_query() -> Statement {
        Statement::new(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?1",
            vec![json!(LEDGER)],
        )
    }

    fn history_query(&self) -> Statement {
        Statement::new(
            "SELECT version,name,checksum FROM _lenso_migrations WHERE owner=?1 AND backend='d1' ORDER BY version",
            vec![json!(self.owner)],
        )
    }

    async fn history(&self, db: &impl Transport) -> Result<Option<Vec<AppliedMigration>>, Error> {
        let rows = query(db, Self::ledger_query()).await?;
        if rows.is_empty() {
            return Ok(None);
        }
        Self::parse_history(query(db, self.history_query()).await?)
    }

    async fn verification_history(
        &self,
        db: &impl Transport,
    ) -> Result<Option<Vec<AppliedMigration>>, Error> {
        // Read existence and exact history in one primary batch. An absent ledger
        // makes the history SELECT fail, so probe only that failure path to retain
        // SetupRequired without treating other storage failures as missing setup.
        let mut rows = match db
            .batch(vec![Self::ledger_query(), self.history_query()])
            .await
        {
            Ok(rows) => rows,
            Err(Error::Transport) => {
                if query(db, Self::ledger_query()).await?.is_empty() {
                    return Ok(None);
                }
                return Err(Error::Transport);
            }
            Err(error) => return Err(error),
        };
        // This fixed two-statement batch is below the capacity limits. Validate
        // its receipt separately so malformed results always remain Transport.
        if rows.len() != 2 {
            return Err(Error::Transport);
        }
        if rows.remove(0).is_empty() {
            return Ok(None);
        }
        Self::parse_history(rows.remove(0))
    }

    fn parse_history(rows: Vec<Value>) -> Result<Option<Vec<AppliedMigration>>, Error> {
        if rows.is_empty() {
            return Ok(None);
        }
        rows.into_iter()
            .map(|r| {
                Ok(AppliedMigration {
                    version: r["version"].as_u64().ok_or(Error::History)?,
                    name: r["name"].as_str().ok_or(Error::History)?.to_owned(),
                    checksum: r["checksum"].as_str().ok_or(Error::History)?.to_owned(),
                })
            })
            .collect::<Result<Vec<_>, _>>()
            .map(Some)
    }

    /// Read-only Ready gate: exact history and legacy marker, no setup or upgrade.
    pub async fn verify(&self, db: &impl Transport) -> Result<(), Error> {
        let history = self
            .verification_history(db)
            .await?
            .ok_or(Error::SetupRequired)?;
        if !self
            .common
            .status(&history)
            .map_err(|_| Error::History)?
            .is_current()
        {
            return Err(Error::UpgradeRequired);
        }
        if let Some(legacy) = self.legacy {
            let rows = query(
                db,
                Statement::new(
                    format!("SELECT version,fingerprint FROM {}", legacy.table),
                    vec![],
                ),
            )
            .await?;
            if rows.len() != 1
                || rows[0]["version"].as_u64() != Some(1)
                || rows[0]["fingerprint"].as_str() != Some(legacy.fingerprint)
            {
                return Err(Error::History);
            }
        }
        Ok(())
    }

    /// Fresh dedicated database only. Existing user tables require explicit adoption.
    pub async fn setup(&self, db: &impl Transport) -> Result<(), Error> {
        if self.history(db).await?.is_some() {
            return self.verify(db).await;
        }
        let rows = query(db, Statement::new(USER_TABLES, vec![])).await?;
        if !rows.is_empty() {
            return Err(Error::Unmanaged);
        }
        self.apply(db, &[], true).await
    }

    pub async fn upgrade(&self, db: &impl Transport) -> Result<(), Error> {
        let history = self.history(db).await?.ok_or(Error::SetupRequired)?;
        self.common.status(&history).map_err(|_| Error::History)?;
        self.apply(db, &history, false).await
    }

    /// Record known v1 without replaying its SQL. Never called by runtime prepare.
    pub async fn adopt_legacy(&self, db: &impl Transport) -> Result<(), Error> {
        if self.history(db).await?.is_some() {
            return self.verify(db).await;
        }
        let legacy = self.legacy.ok_or(Error::Unmanaged)?;
        let first = self.migrations.first().ok_or(Error::InvalidPlan)?.migration;
        let mut batch = self.guarded(&[]);
        batch.push(Self::legacy_guard(legacy));
        batch.push(self.record(first));
        batch.push(Statement::new("DELETE FROM _lenso_migration_guard", vec![]));
        execute(db, batch).await?;
        // Adoption only establishes v1; later upgrades stay explicit.
        let history = self.history(db).await?.ok_or(Error::History)?;
        self.common.status(&history).map_err(|_| Error::History)?;
        Ok(())
    }

    fn legacy_guard(legacy: LegacySchema) -> Statement {
        Statement::new(
            format!(
                "INSERT INTO _lenso_migration_guard(value) SELECT CASE WHEN (SELECT count(*) FROM {})=1 AND EXISTS(SELECT 1 FROM {} WHERE version=1 AND fingerprint=?1) THEN 1 ELSE 0 END",
                legacy.table, legacy.table
            ),
            vec![json!(legacy.fingerprint)],
        )
    }

    fn record(&self, migration: Migration) -> Statement {
        Statement::new(
            "INSERT INTO _lenso_migrations(owner,backend,version,name,checksum) VALUES(?1,'d1',?2,?3,?4)",
            vec![
                json!(self.owner),
                json!(migration.version()),
                json!(migration.name()),
                json!(migration.checksum()),
            ],
        )
    }

    fn guarded(&self, history: &[AppliedMigration]) -> Vec<Statement> {
        let mut batch = vec![
            Statement::new(CREATE_LEDGER, vec![]),
            Statement::new(CREATE_GUARD, vec![]),
        ];
        // Names use the core's ASCII identifier grammar and checksums are hex;
        // ':' and '|' cannot occur in authored fields. One bound prefix avoids
        // exhausting D1's parameter budget as migration history grows.
        let prefix = history
            .iter()
            .map(|row| format!("{}:{}:{}", row.version, row.name, row.checksum))
            .collect::<Vec<_>>()
            .join("|");
        batch.push(Statement::new(
            "INSERT INTO _lenso_migration_guard(value) SELECT CASE WHEN (SELECT COALESCE(group_concat(version || ':' || name || ':' || checksum, '|'), '') FROM (SELECT version,name,checksum FROM _lenso_migrations WHERE owner=?1 AND backend='d1' ORDER BY version))=?2 THEN 1 ELSE 0 END",
            vec![json!(self.owner), json!(prefix)],
        ));
        batch
    }

    async fn apply(
        &self,
        db: &impl Transport,
        history: &[AppliedMigration],
        fresh: bool,
    ) -> Result<(), Error> {
        let pending = self.common.pending(history).map_err(|_| Error::History)?;
        if pending.is_empty() {
            return self.verify(db).await;
        }
        let mut batch = self.guarded(history);
        if fresh {
            // Recheck inside the write transaction: another owner may have set
            // up this database after our read-only preflight. Every owner's
            // ledger must be empty, and no Plugin tables may exist yet.
            batch.push(Statement::new(format!(
                "INSERT INTO _lenso_migration_guard(value) SELECT CASE WHEN NOT EXISTS({USER_TABLES}) AND NOT EXISTS(SELECT 1 FROM _lenso_migrations) THEN 1 ELSE 0 END"
            ), vec![]));
        } else if let Some(legacy) = self.legacy {
            // Runtime verification treats this marker as part of history; an
            // operator must reject its drift before applying pending SQL too.
            batch.push(Self::legacy_guard(legacy));
        }
        for entry in &self.migrations[history.len()..] {
            let mut start = 0;
            for &end in entry.statement_ends {
                batch.push(Statement::new(&entry.migration.sql()[start..end], vec![]));
                start = end;
            }
            batch.push(self.record(entry.migration));
        }
        batch.push(Statement::new("DELETE FROM _lenso_migration_guard", vec![]));
        execute(db, batch).await?;
        self.verify(db).await
    }
}

async fn execute(
    db: &impl Transport,
    statements: Vec<Statement>,
) -> Result<Vec<Vec<Value>>, Error> {
    let count = statements.len();
    if count > 128 || statements.iter().any(|s| s.params.len() > 100) {
        return Err(Error::Capacity);
    }
    let rows = db.batch(statements).await?;
    if rows.len() != count {
        return Err(Error::Transport);
    }
    Ok(rows)
}

async fn query(db: &impl Transport, statement: Statement) -> Result<Vec<Value>, Error> {
    Ok(execute(db, vec![statement]).await?.remove(0))
}
